import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'pt' | 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pt: {
    // Navigation
    'dashboard': 'Dashboard',
    'vehicles': 'Veículos',
    'users': 'Usuários',
    'admin': 'Administração',
    'profile': 'Perfil',
    'logout': 'Sair',
    
    // Dashboard
    'totalToSell': 'Valor Total a Vender',
    'totalSold': 'Valor Total Vendido',
    'carsForSale': 'Carros à Venda',
    'carsSold': 'Carros Vendidos',
    'totalSellers': 'Vendedores Cadastrados',
    'welcome': 'Bem-vindo ao REVENSHOP',
    'subtitle': 'Gerencie seu estoque de veículos com facilidade',
    
    // Vehicles
    'addVehicle': 'Adicionar Veículo',
    'editVehicle': 'Editar Veículo',
    'vehicleName': 'Nome do Veículo',
    'vin': 'Número VIN',
    'year': 'Ano',
    'model': 'Modelo',
    'plate': 'Placa',
    'miles': 'Milhas',
    'internalCode': 'Código Interno',
    'color': 'Cor',
    'caNote': 'Nota CA (0-50)',
    'purchasePrice': 'Valor de Compra',
    'salePrice': 'Valor de Venda',
    'profitMargin': 'Margem de Lucro',
    'minNegotiable': 'Valor Mínimo Negociável',
    'carfaxPrice': 'Valor Carfax',
    'mmrValue': 'Valor MMR',
    'description': 'Descrição',
    'category': 'Categoria',
    'forSale': 'À Venda (Anunciado)',
    'sold': 'Vendido',
    'seller': 'Vendedor',
    'finalSalePrice': 'Valor Final de Venda',
    'actions': 'Ações',
    'edit': 'Editar',
    'duplicate': 'Duplicar',
    'delete': 'Excluir',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'update': 'Atualizar',
    'updating': 'Atualizando',
    'saving': 'Salvando',
    'titleInfo': 'Informações do Título',
    'cleanTitle': 'Título Limpo',
    'rebuiltTitle': 'Título Reconstruído',
    'inHands': 'Em Mãos',
    'inTransit': 'Em Trânsito',
    
    // Users
    'addUser': 'Adicionar Usuário',
    'editUser': 'Editar Usuário',
    'firstName': 'Nome',
    'lastName': 'Sobrenome',
    'email': 'E-mail',
    'phone': 'Telefone',
    'password': 'Senha',
    'confirmPassword': 'Confirmar Senha',
    'role': 'Função',
    'facebook': 'Facebook',
    'photo': 'Foto',
    'commissions': 'Comissões',
    'clientReferral': 'Referência de Cliente',
    'clientBrought': 'Cliente Trazido',
    'fullSale': 'Venda Completa',
    'manageUsers': 'Gerenciar Usuários',
    
    // Login
    'login': 'Entrar',
    'loginTitle': 'Acesso ao Sistema',
    'loginSubtitle': 'Entre com suas credenciais',
    'forgotPassword': 'Esqueceu a senha?',
    'noAccount': 'Não tem conta?',
    'register': 'Cadastre-se',
    
    // Common
    'search': 'Pesquisar',
    'filter': 'Filtrar',
    'loading': 'Carregando...',
    'noData': 'Nenhum dado encontrado',
    'confirm': 'Confirmar',
    'close': 'Fechar',
    'yes': 'Sim',
    'no': 'Não',
    'success': 'Sucesso!',
    'error': 'Erro!',
    'warning': 'Atenção!',
    'info': 'Informação',
    'name': 'Nome',
    'date': 'Data',
    'time': 'Hora',
    'status': 'Status',
    'active': 'Ativo',
    'inactive': 'Inativo',
    'processing': 'Processando...',
    
    // Validations
    'nameRequired': 'Nome é obrigatório',
    'vinRequired': 'VIN é obrigatório',
    'yearRequired': 'Ano é obrigatório',
    'modelRequired': 'Modelo é obrigatório',
    'milesRequired': 'Milhas são obrigatórias',
    'internalCodeRequired': 'Código interno é obrigatório',
    'colorRequired': 'Cor é obrigatória',
    'purchasePriceRequired': 'Valor de compra é obrigatório',
    'salePriceRequired': 'Valor de venda é obrigatório',
    'customerNameRequired': 'Nome do cliente é obrigatório',
    'customerPhoneRequired': 'Telefone do cliente é obrigatório',
    'saleDateRequired': 'Data da venda é obrigatória',
    'milesValidation': 'Milhas devem estar entre 0 e 500,000',
    'caNoteValidation': 'Nota CA deve ser múltiplo de 5 entre 0 e 50',
    'fixRequiredFields': 'Por favor, corrija os campos obrigatórios.',
    'photoWarning': 'Você está tentando salvar muitas fotos. Isso pode tornar o processo mais lento. Deseja continuar?',
    'savingPhotos': 'Salvando fotos. Isso pode levar alguns segundos.',
    'processingPhotos': 'Processando fotos... Isso pode levar alguns minutos.',
    'dontCloseWindow': 'Por favor, não feche esta janela.',
    'descriptionGenerated': 'Descrição gerada automaticamente!',
    'vehicleSaved': 'Veículo salvo com sucesso!',
    
    // Customers
    'customers': 'Clientes',
    'addCustomer': 'Adicionar Cliente',
    'editCustomer': 'Editar Cliente',
    'customerName': 'Nome do Cliente',
    'customerAddress': 'Endereço',
    'customerPhone': 'Telefone',
    'customerEmail': 'E-mail',
    'socialSecurityType': 'Tipo de Documento',
    'socialSecurityNumber': 'Número do Documento',
    'documentPhoto': 'Foto do Documento',
    'reference1': 'Referência Pessoal 1',
    'reference2': 'Referência Pessoal 2',
    'referenceName': 'Nome da Referência',
    'referenceEmail': 'E-mail da Referência',
    'referenceAddress': 'Endereço da Referência',
    'referencePhone': 'Telefone da Referência',
    'responsibleSeller': 'Vendedor Responsável',
    'interestedVehicle': 'Veículo de Interesse',
    'dealStatus': 'Status do Negócio',
    'paymentType': 'Tipo de Pagamento',
    'paymentDetails': 'Detalhes do Pagamento',
    'completedSale': 'Venda Concluída',
    'quote': 'Orçamento',
    'ssn': 'SSN',
    'passport': 'Passaporte',
    'bhph': 'Buy Here Pay Here',
    'financing': 'Financiado',
    'cash': 'À Vista',
    'generateQuote': 'Gerar Orçamento',
    'generateContract': 'Gerar Contrato',
    'printQuote': 'Imprimir Orçamento',
    'exportDeal': 'Exportar Negócio',
    'customerDetails': 'Detalhes do Cliente',
    'vehicleDetails': 'Detalhes do Veículo',
    'dealDetails': 'Detalhes do Negócio',
    'signature': 'Assinatura',
    'signatureDate': 'Data da Assinatura',
    'selectSeller': 'Selecionar Vendedor',
    'selectVehicle': 'Selecionar Veículo',
    'uploadDocument': 'Upload do Documento',
    'totalAmount': 'Valor Total',
    'downPayment': 'Entrada',
    'monthlyPayment': 'Pagamento Mensal',
    'termMonths': 'Prazo (meses)',
    'interestRate': 'Taxa de Juros',
    'managingCustomers': 'Gerenciando clientes e negócios',
  },
  es: {
    // Navigation
    'dashboard': 'Panel',
    'vehicles': 'Vehículos',
    'users': 'Usuarios',
    'admin': 'Administración',
    'profile': 'Perfil',
    'logout': 'Salir',
    
    // Dashboard
    'totalToSell': 'Valor Total a Vender',
    'totalSold': 'Valor Total Vendido',
    'carsForSale': 'Autos en Venta',
    'carsSold': 'Autos Vendidos',
    'totalSellers': 'Vendedores Registrados',
    'welcome': 'Bienvenido a REVENSHOP',
    'subtitle': 'Gestiona tu inventario de vehículos con facilidad',
    
    // Vehicles
    'addVehicle': 'Agregar Vehículo',
    'editVehicle': 'Editar Vehículo',
    'vehicleName': 'Nombre del Vehículo',
    'vin': 'Número VIN',
    'year': 'Año',
    'model': 'Modelo',
    'plate': 'Placa',
    'miles': 'Millas',
    'internalCode': 'Código Interno',
    'color': 'Color',
    'caNote': 'Nota CA (0-50)',
    'purchasePrice': 'Precio de Compra',
    'salePrice': 'Precio de Venta',
    'profitMargin': 'Margen de Ganancia',
    'minNegotiable': 'Precio Mínimo Negociable',
    'carfaxPrice': 'Precio Carfax',
    'mmrValue': 'Valor MMR',
    'description': 'Descripción',
    'category': 'Categoría',
    'forSale': 'En Venta (Anunciado)',
    'sold': 'Vendido',
    'seller': 'Vendedor',
    'finalSalePrice': 'Precio Final de Venta',
    'actions': 'Acciones',
    'edit': 'Editar',
    'duplicate': 'Duplicar',
    'delete': 'Eliminar',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'update': 'Actualizar',
    'updating': 'Actualizando',
    'saving': 'Guardando',
    'titleInfo': 'Información del Título',
    'cleanTitle': 'Título Limpio',
    'rebuiltTitle': 'Título Reconstruido',
    'inHands': 'En Manos',
    'inTransit': 'En Tránsito',
    
    // Users
    'addUser': 'Agregar Usuario',
    'editUser': 'Editar Usuario',
    'firstName': 'Nombre',
    'lastName': 'Apellido',
    'email': 'Correo',
    'phone': 'Teléfono',
    'password': 'Contraseña',
    'confirmPassword': 'Confirmar Contraseña',
    'role': 'Función',
    'facebook': 'Facebook',
    'photo': 'Foto',
    'commissions': 'Comisiones',
    'clientReferral': 'Referencia de Cliente',
    'clientBrought': 'Cliente Traído',
    'fullSale': 'Venta Completa',
    'manageUsers': 'Gestionar Usuarios',
    
    // Login
    'login': 'Iniciar Sesión',
    'loginTitle': 'Acceso al Sistema',
    'loginSubtitle': 'Ingresa con tus credenciales',
    'forgotPassword': '¿Olvidaste tu contraseña?',
    'noAccount': '¿No tienes cuenta?',
    'register': 'Regístrate',
    
    // Common
    'search': 'Buscar',
    'filter': 'Filtrar',
    'loading': 'Cargando...',
    'noData': 'No se encontraron datos',
    'confirm': 'Confirmar',
    'close': 'Cerrar',
    'yes': 'Sí',
    'no': 'No',
    'success': '¡Éxito!',
    'error': '¡Error!',
    'warning': '¡Atención!',
    'info': 'Información',
    'name': 'Nombre',
    'date': 'Fecha',
    'time': 'Hora',
    'status': 'Estado',
    'active': 'Activo',
    'inactive': 'Inactivo',
    'processing': 'Procesando...',
    
    // Validations
    'nameRequired': 'El nombre es obligatorio',
    'vinRequired': 'El VIN es obligatorio',
    'yearRequired': 'El año es obligatorio',
    'modelRequired': 'El modelo es obligatorio',
    'milesRequired': 'Las millas son obligatorias',
    'internalCodeRequired': 'El código interno es obligatorio',
    'colorRequired': 'El color es obligatorio',
    'purchasePriceRequired': 'El precio de compra es obligatorio',
    'salePriceRequired': 'El precio de venta es obligatorio',
    'customerNameRequired': 'El nombre del cliente es obligatorio',
    'customerPhoneRequired': 'El teléfono del cliente es obligatorio',
    'saleDateRequired': 'La fecha de venta es obligatoria',
    'milesValidation': 'Las millas deben estar entre 0 y 500,000',
    'caNoteValidation': 'La nota CA debe ser múltiplo de 5 entre 0 y 50',
    'fixRequiredFields': 'Por favor, corrija los campos obligatorios.',
    'photoWarning': 'Está intentando guardar muchas fotos. Esto puede hacer más lento el proceso. ¿Desea continuar?',
    'savingPhotos': 'Guardando fotos. Esto puede tomar algunos segundos.',
    'processingPhotos': 'Procesando fotos... Esto puede tomar algunos minutos.',
    'dontCloseWindow': 'Por favor, no cierre esta ventana.',
    'descriptionGenerated': '¡Descripción generada automáticamente!',
    'vehicleSaved': '¡Vehículo guardado con éxito!',
    
    // Customers
    'customers': 'Clientes',
    'addCustomer': 'Agregar Cliente',
    'editCustomer': 'Editar Cliente',
    'customerName': 'Nombre del Cliente',
    'customerAddress': 'Dirección',
    'customerPhone': 'Teléfono',
    'customerEmail': 'Correo Electrónico',
    'socialSecurityType': 'Tipo de Documento',
    'socialSecurityNumber': 'Número de Documento',
    'documentPhoto': 'Foto del Documento',
    'reference1': 'Referencia Personal 1',
    'reference2': 'Referencia Personal 2',
    'referenceName': 'Nombre de la Referencia',
    'referenceEmail': 'Correo de la Referencia',
    'referenceAddress': 'Dirección de la Referencia',
    'referencePhone': 'Teléfono de la Referencia',
    'responsibleSeller': 'Vendedor Responsable',
    'interestedVehicle': 'Vehículo de Interés',
    'dealStatus': 'Estado del Negocio',
    'paymentType': 'Tipo de Pago',
    'paymentDetails': 'Detalles del Pago',
    'completedSale': 'Venta Completada',
    'quote': 'Cotización',
    'ssn': 'SSN',
    'passport': 'Pasaporte',
    'bhph': 'Buy Here Pay Here',
    'financing': 'Financiado',
    'cash': 'Al Contado',
    'generateQuote': 'Generar Cotización',
    'generateContract': 'Generar Contrato',
    'printQuote': 'Imprimir Cotización',
    'exportDeal': 'Exportar Negocio',
    'customerDetails': 'Detalles del Cliente',
    'vehicleDetails': 'Detalles del Vehículo',
    'dealDetails': 'Detalles del Negocio',
    'signature': 'Firma',
    'signatureDate': 'Fecha de Firma',
    'selectSeller': 'Seleccionar Vendedor',
    'selectVehicle': 'Seleccionar Vehículo',
    'uploadDocument': 'Subir Documento',
    'totalAmount': 'Monto Total',
    'downPayment': 'Enganche',
    'monthlyPayment': 'Pago Mensual',
    'termMonths': 'Plazo (meses)',
    'interestRate': 'Tasa de Interés',
    'managingCustomers': 'Gestionando clientes y negocios',
  },
  en: {
    // Navigation
    'dashboard': 'Dashboard',
    'vehicles': 'Vehicles',
    'users': 'Users',
    'admin': 'Administration',
    'profile': 'Profile',
    'logout': 'Logout',
    
    // Dashboard
    'totalToSell': 'Total Value to Sell',
    'totalSold': 'Total Value Sold',
    'carsForSale': 'Cars for Sale',
    'carsSold': 'Cars Sold',
    'totalSellers': 'Registered Sellers',
    'welcome': 'Welcome to REVENSHOP',
    'subtitle': 'Manage your vehicle inventory with ease',
    
    // Vehicles
    'addVehicle': 'Add Vehicle',
    'editVehicle': 'Edit Vehicle',
    'vehicleName': 'Vehicle Name',
    'vin': 'VIN Number',
    'year': 'Year',
    'model': 'Model',
    'plate': 'Plate',
    'miles': 'Miles',
    'internalCode': 'Internal Code',
    'color': 'Color',
    'caNote': 'CA Note (0-50)',
    'purchasePrice': 'Purchase Price',
    'salePrice': 'Sale Price',
    'profitMargin': 'Profit Margin',
    'minNegotiable': 'Minimum Negotiable',
    'carfaxPrice': 'Carfax Price',
    'mmrValue': 'MMR Value',
    'description': 'Description',
    'category': 'Category',
    'forSale': 'For Sale (Listed)',
    'sold': 'Sold',
    'seller': 'Seller',
    'finalSalePrice': 'Final Sale Price',
    'actions': 'Actions',
    'edit': 'Edit',
    'duplicate': 'Duplicate',
    'delete': 'Delete',
    'save': 'Save',
    'cancel': 'Cancel',
    'update': 'Update',
    'updating': 'Updating',
    'saving': 'Saving',
    'titleInfo': 'Title Information',
    'cleanTitle': 'Clean Title',
    'rebuiltTitle': 'Rebuilt Title',
    'inHands': 'In Hands',
    'inTransit': 'In Transit',
    
    // Users
    'addUser': 'Add User',
    'editUser': 'Edit User',
    'firstName': 'First Name',
    'lastName': 'Last Name',
    'email': 'Email',
    'phone': 'Phone',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'role': 'Role',
    'facebook': 'Facebook',
    'photo': 'Photo',
    'commissions': 'Commissions',
    'clientReferral': 'Client Referral',
    'clientBrought': 'Client Brought',
    'fullSale': 'Full Sale',
    'manageUsers': 'Manage Users',
    
    // Login
    'login': 'Login',
    'loginTitle': 'System Access',
    'loginSubtitle': 'Enter your credentials',
    'forgotPassword': 'Forgot password?',
    'noAccount': "Don't have an account?",
    'register': 'Register',
    
    // Common
    'search': 'Search',
    'filter': 'Filter',
    'loading': 'Loading...',
    'noData': 'No data found',
    'confirm': 'Confirm',
    'close': 'Close',
    'yes': 'Yes',
    'no': 'No',
    'success': 'Success!',
    'error': 'Error!',
    'warning': 'Warning!',
    'info': 'Information',
    'name': 'Name',
    'date': 'Date',
    'time': 'Time',
    'status': 'Status',
    'active': 'Active',
    'inactive': 'Inactive',
    'processing': 'Processing...',
    
    // Validations
    'nameRequired': 'Name is required',
    'vinRequired': 'VIN is required',
    'yearRequired': 'Year is required',
    'modelRequired': 'Model is required',
    'milesRequired': 'Miles are required',
    'internalCodeRequired': 'Internal code is required',
    'colorRequired': 'Color is required',
    'purchasePriceRequired': 'Purchase price is required',
    'salePrice is required',
    'customerNameRequired': 'Customer name is required',
    'customerPhoneRequired': 'Customer phone is required',
    'saleDateRequired': 'Sale date is required',
    'milesValidation': 'Miles must be between 0 and 500,000',
    'caNoteValidation': 'CA Note must be a multiple of 5 between 0 and 50',
    'fixRequiredFields': 'Please fix the required fields.',
    'photoWarning': 'You are trying to save many photos. This may slow down the process. Do you want to continue?',
    'savingPhotos': 'Saving photos. This may take a few seconds.',
    'processingPhotos': 'Processing photos... This may take a few minutes.',
    'dontCloseWindow': 'Please do not close this window.',
    'descriptionGenerated': 'Description generated automatically!',
    'vehicleSaved': 'Vehicle saved successfully!',
    
    // Customers
    'customers': 'Customers',
    'addCustomer': 'Add Customer',
    'editCustomer': 'Edit Customer',
    'customerName': 'Customer Name',
    'customerAddress': 'Address',
    'customerPhone': 'Phone',
    'customerEmail': 'Email',
    'socialSecurityType': 'Document Type',
    'socialSecurityNumber': 'Document Number',
    'documentPhoto': 'Document Photo',
    'reference1': 'Personal Reference 1',
    'reference2': 'Personal Reference 2',
    'referenceName': 'Reference Name',
    'referenceEmail': 'Reference Email',
    'referenceAddress': 'Reference Address',
    'referencePhone': 'Reference Phone',
    'responsibleSeller': 'Responsible Seller',
    'interestedVehicle': 'Interested Vehicle',
    'dealStatus': 'Deal Status',
    'paymentType': 'Payment Type',
    'paymentDetails': 'Payment Details',
    'completedSale': 'Completed Sale',
    'quote': 'Quote',
    'ssn': 'SSN',
    'passport': 'Passport',
    'bhph': 'Buy Here Pay Here',
    'financing': 'Financing',
    'cash': 'Cash',
    'generateQuote': 'Generate Quote',
    'generateContract': 'Generate Contract',
    'printQuote': 'Print Quote',
    'exportDeal': 'Export Deal',
    'customerDetails': 'Customer Details',
    'vehicleDetails': 'Vehicle Details',
    'dealDetails': 'Deal Details',
    'signature': 'Signature',
    'signatureDate': 'Signature Date',
    'selectSeller': 'Select Seller',
    'selectVehicle': 'Select Vehicle',
    'uploadDocument': 'Upload Document',
    'totalAmount': 'Total Amount',
    'downPayment': 'Down Payment',
    'monthlyPayment': 'Monthly Payment',
    'termMonths': 'Term (months)',
    'interestRate': 'Interest Rate',
    'managingCustomers': 'Managing customers and deals',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('pt');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
