// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctdajbfmgmkhqueskjvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0ZGFqYmZtZ21raHF1ZXNranZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMDU3MDAsImV4cCI6MjA2NDU4MTcwMH0.YhylL0b50ku_vz6CXJ_ap91R05IW8B4vv75KorqmXAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);